### ISSUE TITLE
Lumen - Error on Setting Up

### ISSUE THREAD

**Issue by memoishin** [ytake/Laravel-Aspect#53]
I am using Lumen 5.6. When I run any commands or access any functions through Postman I get this error:

`Class 'App\Providers\AnnotationConfiguration' not found`

When I added this `use Ytake\LaravelAspect\AnnotationConfiguration;` in AspectServiceProvider.php, the above issue resolved but now I am getting this error.

`Type error: Argument 1 passed to Ytake\LaravelAspect\AnnotationConfiguration::__construct() must be of the type array, null given, called
  in C:\Projects\cs415_api\app\Providers\AspectServiceProvider.php on line 22`

I suspect that the following line in AspectServiceProvider returns null.

`$app['config']->get('ytake-laravel-aop.annotation')`

Any ideas on how to resolve this error?

**Comment by ytake** [comment]
@memoishin 

# example 

You will have to create a config/ytake-laravel-aop.php file and copy the contents from the package config.

create `App\Providers\AspectServiceProvider` class

```php
<?php
declare(strict_types=1);

namespace App\Providers;

use Ytake\LaravelAspect\AspectServiceProvider as AspectProvider;
use Ytake\LaravelAspect\AnnotationConfiguration;
use Ytake\LaravelAspect\AspectManager;

/**
 * Class AspectServiceProvider
 */
class AspectServiceProvider extends AspectProvider
{
    /**
     * {@inheritdoc}
     */
    public function register()
    {
        $this->app->configure('ytake-laravel-aop');
        $this->app->singleton('aspect.manager', function ($app) {
            $annotationConfiguration = new AnnotationConfiguration(
                $app['config']->get('ytake-laravel-aop.annotation')
            );
            $annotationConfiguration->ignoredAnnotations();

            // register annotation
            return new AspectManager($app);
        });
    }
}

```

Add this service provider to your `bootstrap/app.php`  file.

```php
$app->register(\App\Providers\AspectServiceProvider::class);
$app->register(\Ytake\LaravelAspect\ConsoleServiceProvider::class);
```

## publish aspect module class

```bash
$ php artisan ytake:aspect-module-publish
```

**Comment by memoishin** [comment]
I am now able to run `php artisan ytake:aspect-module-publish` without errors.

Thank You for your answer.
