### ISSUE TITLE
Every modules are not working.

### ISSUE THREAD

**Issue by seungmun** [ytake/Laravel-Aspect#54]
I installed fully like how documentation to do.

and, no errors, but not working every modules even I re-installed for several times.

also installing it with Laravel 5.6 we got 'ikic/php-parser' dependency error.

**Comment by ytake** [comment]
@seungmun 
Thanks for dependency error report.
released v2.1.1 (for Laravel5.6), v2.0.2 (for Laravel5.5 LTS)

**Comment by seungmun** [comment]
Thanks for your fast reply 👍 
I will give some contribution next if it gets some error :)
